function [colours] = GetRGBValuesForPoints(imageArray, kPoints)
% GetRGBValuesForPoints.m retrives the Red, Blue and Green values of
% positions in a 3D image array. These positions, kPoints, are generated in
% the SelectKRandomPoints.m function
% Inputs:   imageArray = 3D Image Array (RGB format)
%           kPoints = kPoints array generated by SelectKRandomPoints.m
% Outputs:  colours = 3D array of colour data
% Author: Jack Chamberlain


[kPointsRows, ~] = size(kPoints);

% Preallocating colours array
colours = zeros(kPointsRows,1,3);


for i = 1:kPointsRows % obtains each point stored in kPoints
    pointRow = kPoints(i, 1);
    pointCol = kPoints(i, 2);
    
    % Appends the points RGB values to the colours 3D array
    colours(i,1,1) = imageArray(pointRow, pointCol, 1);% red
    colours(i,1,2) = imageArray(pointRow, pointCol, 2);% green
    colours(i,1,3) = imageArray(pointRow, pointCol, 3);% blue
end